// ### AJUSTE DE VARIÁVEIS PARA ALGORITMOS ###

// ###### seguir parede ######

#define SHARP_DIFF 5
#define DIST_TURN0 10
#define LOOKING_SPEED 180
#define ADJUSTING_SPEED1 200
#define ADJUSTING_SPEED2 150
#define TEMPO_DE_RE 100
#define TURNING_SPEED 200